### ISSUE TITLE
ZT fails to build on OpenBSD 6.2

### ISSUE THREAD

**Issue by betabrain** [zerotier/ZeroTierOne#639]
Currently the dev branch fails to build on OpenBSD. I have verified that the breaking changes were introduced in 16613ab. I first posted this in https://github.com/zerotier/ZeroTierOne/issues/439#issuecomment-349147031.
```
# gmake
[...]
eg++ -O3 -fstack-protector -Wall -fPIE -fvisibility=hidden -fstack-protector -pthread  -DNDEBUG  -DZT_USE_X64_ASM_SALSA2012 -DZT_BUILD_PLATFORM=9 -DZT_BUILD_ARCHITECTURE=2 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -fno-rtti -std=c++11    -c -o node/Trace.o node/Trace.cpp
node/Trace.cpp: In function 'void ZeroTier::ZT_LOCAL_TRACE(void*, const ZeroTier::RuntimeEnvironment*, const char*, ...)':
node/Trace.cpp:49:2: error: 'va_list' was not declared in this scope
  va_list ap;
  ^
node/Trace.cpp:50:11: error: 'ap' was not declared in this scope
  va_start(ap,fmt);
           ^
node/Trace.cpp:50:17: error: 'va_start' was not declared in this scope
  va_start(ap,fmt);
                 ^
node/Trace.cpp:52:11: error: 'va_end' was not declared in this scope
  va_end(ap);
           ^
gmake: *** [<builtin>: node/Trace.o] Error 1
```
The toolchain used to build ZT on OpenBSD 6.2 is:
- GNU Make 4.2.1
- eg++ (GCC) 4.9.4
- egcc (GCC) 4.9.4

**Comment by jungle-boogie** [comment]
I was able to build openBSD today.

**Comment by betabrain** [comment]
I can confirm that as of f13886d ZT builds again on OpenBSD.
