### ISSUE TITLE
Failing to compile on ARM64 Linux

### ISSUE THREAD

**Issue by neofeo** [zerotier/ZeroTierOne#1406]
I failed to compile on lastest release on ubuntu 20.04 at the stage of crypto
Hardware : RK3399 running on kernel 5.10.35

lot of this:
```
/home/pi/Downloads/ZeroTierOne-1.6.5/node/AES_armcrypto.cpp:189:19: note: called from here
  189 |    d2 = vaesmcq_u8(vaeseq_u8(d2, k0));
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from /home/pi/Downloads/ZeroTierOne-1.6.5/node/Constants.hpp:121,
                 from /home/pi/Downloads/ZeroTierOne-1.6.5/node/AES_armcrypto.cpp:14:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h:12452:1: error: inlining failed in call to always_inline ‘uint8x16_t vaesmcq_u8(uint8x16_t)’: target specific option mismatch
12452 | vaesmcq_u8 (uint8x16_t data)
      | ^~~~~~~~~~
/home/pi/Downloads/ZeroTierOne-1.6.5/node/AES_armcrypto.cpp:188:19: note: called from here
  188 |    d1 = vaesmcq_u8(vaeseq_u8(d1, k0));
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from /home/pi/Downloads/ZeroTierOne-1.6.5/node/Constants.hpp:121,
                 from /home/pi/Downloads/ZeroTierOne-1.6.5/node/AES_armcrypto.cpp:14:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h:12438:1: error: inlining failed in call to always_inline ‘uint8x16_t vaeseq_u8(uint8x16_t, uint8x16_t)’: target specific option mismatch
12438 | vaeseq_u8 (uint8x16_t data, uint8x16_t key)
      | ^~~~~~~~~
/home/pi/Downloads/ZeroTierOne-1.6.5/node/AES_armcrypto.cpp:188:19: note: called from here
  188 |    d1 = vaesmcq_u8(vaeseq_u8(d1, k0));
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from /home/pi/Downloads/ZeroTierOne-1.6.5/node/Constants.hpp:121,
                 from /home/pi/Downloads/ZeroTierOne-1.6.5/node/AES_armcrypto.cpp:14:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h:12452:1: error: inlining failed in call to always_inline ‘uint8x16_t vaesmcq_u8(uint8x16_t)’: target specific option mismatch
12452 | vaesmcq_u8 (uint8x16_t data)
      | ^~~~~~~~~~
/home/pi/Downloads/ZeroTierOne-1.6.5/node/AES_armcrypto.cpp:187:19: note: called from here
  187 |    d0 = vaesmcq_u8(vaeseq_u8(d0, k0));
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from /home/pi/Downloads/ZeroTierOne-1.6.5/node/Constants.hpp:121,
                 from /home/pi/Downloads/ZeroTierOne-1.6.5/node/AES_armcrypto.cpp:14:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h:12438:1: error: inlining failed in call to always_inline ‘uint8x16_t vaeseq_u8(uint8x16_t, uint8x16_t)’: target specific option mismatch
12438 | vaeseq_u8 (uint8x16_t data, uint8x16_t key)
      | ^~~~~~~~~
```

**Comment by joseph-henry** [comment]
I'm not too familiar with this part of the codebase and I know this likely isn't a long-term solution for you but you can try disabling the hardware acceleration by uncommenting this line:

https://github.com/zerotier/ZeroTierOne/blob/6faca86bb424d0b9643b6efa50571f73310d8276/node/AES.hpp#L22

Maybe @adamierymenko has a better idea.

**Comment by neofeo** [comment]
can we discard encryption inside the prgoram? soft decryption will be ..too much

**Comment by neofeo** [comment]
closing. it works fine without invoking cmake from a different folder.
