### ISSUE TITLE
Does not build/run on OpenBSD

### ISSUE THREAD

**Issue by jungle-boogie** [zerotier/ZeroTierOne#439]
Hello,

Attempting to build ZT from master on openbsd -current:

```
c++ -O3 -fstack-protector -Wall -fPIE -fvisibility=hidden -fstack-protector -pthread  -DNDEBUG  -fno-rtti   -c -o service/ControlPlane.o service/ControlPlane.cpp
c++ -O3 -fstack-protector -Wall -fPIE -fvisibility=hidden -fstack-protector -pthread  -DNDEBUG  -fno-rtti   -c -o osdep/BSDEthernetTap.o osdep/BSDEthernetTap.cpp
osdep/BSDEthernetTap.cpp: In member function 'void ZeroTier::BSDEthernetTap::scanMulticastGroups(std::vector<ZeroTier::MulticastGroup, std::allocator<ZeroTier::MulticastGroup> >&, std::vector<ZeroTier::MulticastGroup, std::allocator<ZeroTier::MulticastGroup> >&)':
osdep/BSDEthernetTap.cpp:329: error: 'getifmaddrs' was not declared in this scope
osdep/BSDEthernetTap.cpp:332: error: invalid use of incomplete type 'struct ZeroTier::ifmaddrs'
osdep/BSDEthernetTap.cpp:328: error: forward declaration of 'struct ZeroTier::ifmaddrs'
osdep/BSDEthernetTap.cpp:333: error: invalid use of incomplete type 'struct ZeroTier::ifmaddrs'
osdep/BSDEthernetTap.cpp:328: error: forward declaration of 'struct ZeroTier::ifmaddrs'
osdep/BSDEthernetTap.cpp:334: error: invalid use of incomplete type 'struct ZeroTier::ifmaddrs'
osdep/BSDEthernetTap.cpp:328: error: forward declaration of 'struct ZeroTier::ifmaddrs'
osdep/BSDEthernetTap.cpp:338: error: invalid use of incomplete type 'struct ZeroTier::ifmaddrs'
osdep/BSDEthernetTap.cpp:328: error: forward declaration of 'struct ZeroTier::ifmaddrs'
osdep/BSDEthernetTap.cpp:340: error: 'freeifmaddrs' was not declared in this scope
gmake: *** [<builtin>: osdep/BSDEthernetTap.o] Error 1
```

**Comment by adamierymenko** [comment]
We've actually never ported to OpenBSD. It's quite possible but would likely involve some ifdefs. Maybe we can look at it for 1.2.0 if we have time.

**Comment by adamierymenko** [comment]
Fixed in `dev`. Now builds and runs. There may be a limit of 4 network memberships due to there only being 4 taps.

**Comment by adamierymenko** [comment]
Only tested on latest OpenBSD 6.0. Note that you need to pkg_add gcc, g++, and gmake to get g++ 4.9.3 since older g++ is too old.

**Comment by adamierymenko** [comment]
Also must use gmake.

**Comment by jungle-boogie** [comment]
Yes, builds with openbsd 6.0-current.

Now something needs to change with freebsd. Not quite sure how to link gmake to gcc49.

**Comment by adamierymenko** [comment]
Seems to build out of the box on FreeBSD 11 for us. Will check again.

**Comment by adamierymenko** [comment]
Hmm... spoke too soon. Weird.

**Comment by jungle-boogie** [comment]
Gcc is installed with:
`pkg install gcc49`, which installs to `/usr/local/bin/gcc49`.

Does the makefile need to be updated for this path?

**Comment by adamierymenko** [comment]
On FreeBSD-11 gcc49 is the default.

I think I found it. C++ needs `-D_GLIBCXX_USE_C99` `-D_GLIBCXX_USE_C99_MATH` `-D_GLIBCXX_USE_C99_MATH_TR1`. Will commit after we test.

**Comment by adamierymenko** [comment]
On FreeBSD-10 you might have to `gmake CXX=g++49 CC=gcc49` or something

**Comment by adamierymenko** [comment]
Just pushed. Should be good.

**Comment by adamierymenko** [comment]
Still works on OpenBSD too, so we are good to go.

**Comment by jungle-boogie** [comment]
No to pester you, @adamierymenko, but how did you build under FBSD11 without `gmake CXX=g++49 CC=gcc49`?

**Comment by betabrain** [comment]
Hello, I just tried building ZT on **OpenBSD 6.2** and got the following:

```
# git status
On branch dev
Your branch is up-to-date with 'origin/dev'.

nothing to commit, working tree clean

# git log -1 | cat
commit 16613ab5fb5a1f6cb1271ae67e68836a1898023d
Author: Adam Ierymenko <adam.ierymenko@gmail.com>
Date:   Mon Dec 4 14:40:10 2017 -0800

    Clean up remote tracing code, add per-network remote trace settings, add remote trace level, and make local trace output readable again.

# egcc --version
egcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# eg++ --version
eg++ (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# gmake --version
GNU Make 4.2.1
Built for x86_64-unknown-openbsd6.2
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

# gmake -f make-bsd.mk CC=egcc CXX=eg++ selftest
eg++ -O3 -fstack-protector -Wall -fPIE -fvisibility=hidden -fstack-protector -pthread  -DNDEBUG  -DZT_USE_X64_ASM_SALSA2012 -DZT_BUILD_PLATFORM= -DZT_BUILD_ARCHITECTURE=2 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -fno-rtti -std=c++11    -c -o node/Trace.o node/Trace.cpp

node/Trace.cpp: In function 'void ZeroTier::ZT_LOCAL_TRACE(void*, const ZeroTier::RuntimeEnvironment*, const char*, ...)':
node/Trace.cpp:49:2: error: 'va_list' was not declared in this scope
  va_list ap;
  ^
node/Trace.cpp:50:11: error: 'ap' was not declared in this scope
  va_start(ap,fmt);
           ^
node/Trace.cpp:50:17: error: 'va_start' was not declared in this scope
  va_start(ap,fmt);
                 ^
node/Trace.cpp:52:11: error: 'va_end' was not declared in this scope
  va_end(ap);
           ^
gmake: *** [<builtin>: node/Trace.o] Error 1
```
What am I getting wrong? Is this me or something in ZT? Any help is appreciated.

**Comment by jungle-boogie** [comment]
> gmake -f make-bsd.mk CC=egcc CXX=eg++ selftest

I just perform `gmake`.

What's this report:
`freebsd-version -ku`

**Comment by betabrain** [comment]
Same outcome... I am on **OpenBSD 6.2**, the architecture is **amd64**, running **GENERIC.MP#134**
```
# gmake
eg++ -O3 -fstack-protector -Wall -fPIE -fvisibility=hidden -fstack-protector -pthread  -DNDEBUG  -DZT_USE_X64_ASM_SALSA2012 -DZT_BUILD_PLATFORM=9 -DZT_BUILD_ARCHITECTURE=2 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -fno-rtti -std=c++11    -c -o node/Trace.o node/Trace.cpp
node/Trace.cpp: In function 'void ZeroTier::ZT_LOCAL_TRACE(void*, const ZeroTier::RuntimeEnvironment*, const char*, ...)':
node/Trace.cpp:49:2: error: 'va_list' was not declared in this scope
  va_list ap;
  ^
node/Trace.cpp:50:11: error: 'ap' was not declared in this scope
  va_start(ap,fmt);
           ^
node/Trace.cpp:50:17: error: 'va_start' was not declared in this scope
  va_start(ap,fmt);
                 ^
node/Trace.cpp:52:11: error: 'va_end' was not declared in this scope
  va_end(ap);
           ^
gmake: *** [<builtin>: node/Trace.o] Error 1
```

**Comment by jungle-boogie** [comment]
I'm on openbsd -current and it complied fine for me. I'll try again tonight. Can you go back a few commits and see if it compiles?

**Comment by betabrain** [comment]
I went back to dev~10 [4166d8ca]. No more errors. 😄  I have yet to find out which commit introduced the errors.

**Comment by jungle-boogie** [comment]
I'd say you need to open a new issue. There was a recent commit to node/trace.cpp and it may have introduced this error: https://github.com/zerotier/ZeroTierOne/commit/16613ab5fb5a1f6cb1271ae67e68836a1898023d

I can't connect to my openBSD machine ATM, but I'd assume it would also fail for me. I didn't see there was a new commit from yesterday, so that's why I thought it was fine. checkout the commit before the one above and see if it builds, but report that in the new issue.

**Comment by betabrain** [comment]
Done, see #639. Thanks for your help.
