### ISSUE TITLE
OpenBSD build hangs at 100% CPU on startup

### ISSUE THREAD

**Issue by dch** [zerotier/ZeroTierOne#987]
**Describe the bug**

On first startup with clean /var/db/zerotier-one dir, zt pegs cpu at 100% and never gets going. 

- Using a debug build, no output is seen so we are getting stuck quite early.
- Only authtoken.secret and zerotier-one.pid are created.
- the port is not yet registered

```
$ uname -a
OpenBSD flatline.skunkwerks.at 6.5 GENERIC.MP#3 amd64
$ pkg_info gcc
Information for inst:gcc-4.9.4p18
 sysctl hw (abridged)
hw.machine=amd64
hw.model=Intel(R) Atom(TM) CPU C2558 @ 2.40GHz
hw.ncpu=4
hw.cpuspeed=2400
hw.physmem=8559362048
hw.usermem=8559349760
hw.smt=0
```

**To Reproduce**

- git clone zt & checkout 1.4.0 tag.
- `doas pkg_install gcc g++` & pick the 4.9 versions
- `gmake debug && doas gmake install`
- `doas zerotier-one /var/db/zerotier-one &`
- watch top in another window and cry
- check /var/db/zerotier-one for usual files

**Expected behavior**

- cpu is not pegged
- zt startup works as expected in 1.2.12

**Other info**

It would be sensible to add a couple of lines of output indicating progress during startup.
I was unable to compile zt with gcc8.3.0

**Comment by chairmanwow** [comment]
Also does this when compiled with `clang` and `clang++` unsurprisingly.

**Comment by dch** [comment]
FWIW the 100% CPU peg bug still happens with #1031 so let's not close this when that is merged.

**Comment by rjmalagon** [comment]
I wish to help in the debug process of this glitch.
I really tried to debug with llvm and gcc builds directly from the master git code without success, the daemon just locks with peek CPU usage void of meaningful error codes. It seems something unexpectedly nasty in the TAP code in BSDEthernetTap.cpp does not fit in the current OpenBSD distro.
Any tip on how to debug to help the developers is welcome.

**Comment by rjmalagon** [comment]
I try to compile the edge branch, known to have many changes.
Unfortunately fails to compile

`[ 32%] Building CXX object core/CMakeFiles/zt_core.dir/Certificate.cpp.o
In file included from /root/Code/ZeroTierOne/core/Certificate.cpp:14:
In file included from /root/Code/ZeroTierOne/core/Certificate.hpp:23:
In file included from /root/Code/ZeroTierOne/core/Locator.hpp:18:
/root/Code/ZeroTierOne/core/Endpoint.hpp:32:1: error: static_assert failed due to requirement '(192 - 1) > sizeof(ZeroTier::InetAddress)'
      "ZT_ENDPOINT_MARSHAL_SIZE_MAX not large enough"
static_assert((ZT_ENDPOINT_MARSHAL_SIZE_MAX - 1) > sizeof(InetAddress), "ZT_ENDPOINT_MARSHAL_SIZE_MAX not large enough");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
`
I really tried to tweak ZT_ENDPOINT_MARSHAL_SIZE_MAX , and make the compiler to continue a bit more. And ugly hack only to see ahead but I acknowledge that I am ignorant about this code.

**Comment by glimberg** [comment]
@rjmalagon The `edge` branch is still under heavy development and is not ready for end user use yet

**Comment by rjmalagon** [comment]
@glimberg Yes, was just a test. Unfortunately main branch does not work in OpenBSD and currently hard to debug.

**Comment by rjmalagon** [comment]
Just to update.
Zerotier 1.6.2 works correctly in OpenBSD 6.8
Just needs some changes at the build process, it does not compile with GCC. Works fine with Clang.

To compile I replace the compiler in the Makefile
`
ifeq ($(OSTYPE),OpenBSD)
	CC=clang
	CXX=clang++
	ZT_BUILD_PLATFORM=9
	include make-bsd.mk
`
Thanks to all developers for the progress.

**Comment by cspiegel** [comment]
The latest version (1.16.0) successfully builds and runs, without modification, on OpenBSD 7.8. I've got it running with no issues, including no excessive CPU usage.

Closing this issue as everything works as expected now; please open a new one if you continue to run into problems.
