### ISSUE TITLE
Build of 1.8.9 fails in yocto

### ISSUE THREAD

**Issue by theodiem** [zerotier/ZeroTierOne#1663]
- What you expect to be happening.
Build is successful. Used to work with 1.8.6

- What is actually happening?
Build fails in yocto with:
```
|      Running `rustc --crate-name proc_macro2 --edition=2018 /build/tmp/work/corei7-64-poky-linux/cargo/1.59.0-r0/rustc-1.59.0-src/vendor/proc-macro2-1.0.30/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=a2893b83ba2368c5 -C extra-filename=-a2893b83ba2368c5 --out-dir /build/tmp/work/corei7-64-poky-linux/cargo/1.59.0-r0/build/target/x86_64-poky-linux/release/deps --target x86_64-poky-linux -C linker=/build/tmp/work/corei7-64-poky-linux/cargo/1.59.0-r0/wrapper/target-rust-ccld -L dependency=/build/tmp/work/corei7-64-poky-linux/cargo/1.59.0-r0/build/target/x86_64-poky-linux/release/deps -L dependency=/build/tmp/work/corei7-64-poky-linux/cargo/1.59.0-r0/build/target/release/deps --extern unicode_xid=/build/tmp/work/corei7-64-poky-linux/cargo/1.59.0-r0/build/target/x86_64-poky-linux/release/deps/libunicode_xid-ac711f19de6cb44c.rmeta --cap-lints allow -L /build/tmp/work/corei7-64-poky-linux/cargo/1.59.0-r0/recipe-sysroot/usr/lib/rust --remap-path-prefix=/build/tmp/work/corei7-64-poky-linux/cargo/1.59.0-r0=/usr/src/debug/cargo/1.59.0-r0 --cfg lexerror_display --cfg hygiene --cfg literal_from_str --cfg is_available --cfg use_proc_macro --cfg wrap_proc_macro`
| error[E0463]: can't find crate for `proc_macro`
|    --> /usr/src/debug/cargo/1.59.0-r0/rustc-1.59.0-src/vendor/proc-macro2-1.0.30/src/lib.rs:102:1
|     |
| 102 | extern crate proc_macro;
|     | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

```
- Any steps to reproduce the error.
Used the following recipe:
```
# based on https://github.com/OpenPLi/openpli-oe-core/blob/develop/meta-openpli/recipes-connectivity/zerotier/zerotier_1.4.6.bb
SUMMARY = "A Smart Ethernet Switch for Earth"
MAINTAINER = "https://github.com/zerotier/ZeroTierOne"
DESCRIPTION = "Create flat virtual Ethernet networks of almost unlimited size"
HOMEPAGE = "https://www.zerotier.com"
SECTION = "net"
LICENSE = "BUSL-1.1"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=9a913ad4fdae889b528bc6213633b24c"

SRCREV = "7ea2354540cd891f61d0944ff8a25c53a42bd038"
SRC_URI = "git://github.com/zerotier/ZeroTierOne.git;branch=master;protocol=https"

S = "${WORKDIR}/git"

inherit update-rc.d systemd gitpkgv autotools-brokensep

INITSCRIPT_NAME = "zerotier-one"
SYSTEMD_SERVICE:${PN} = "zerotier-one.service"

TARGET_CC_ARCH += "${LDFLAGS}"
TARGET_CFLAGS += "-fpic"
INSANE_SKIP:${PN} += "already-stripped"

# https://github.com/zerotier/ZeroTierOne/issues/1179
TARGET_LDFLAGS += "-z noexecstack"

DEPENDS += " cargo"
RDEPENDS:${PN} = "kernel-module-tun"

do_install:append() {
    if ${@bb.utils.contains('DISTRO_FEATURES','systemd','true','false',d)}; then
        install -D -m 0644 ${S}/debian/zerotier-one.service ${D}${systemd_system_unitdir}/zerotier-one.service
    else
        install -D -m 0755 ${S}/debian/zerotier-one.init ${D}${sysconfdir}/init.d/zerotier-one
    fi
}

```
- Any relevant console output or screenshots.
Besides the mentioned build error, I've found a similar discussion at https://github.com/dtolnay/proc-macro-hack/issues/6
If needed I can try to build a branch in my setup and report, but I'm not familiar with rust to investigate it much further.

- What operating system and ZeroTier version. Please try the latest ZeroTier release. 
Building zerotier 1.8.9 release, on yocto linux 4.0 (kirkstone)

**Comment by theodiem** [comment]
Closing issue since bug is when yocto is building cargo, not yet on zerotier. Sorry for the mess.
